export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DEcREMENT_COUNTER";

export const GET_VALUE = "GET_VALUE";
export const ADD_MEDICINCES = "ADD_MEDICINCES";
export const DELETE_MEDICINCES = "DELETE_MEDICINCES";
export const UPDATE_MEDICINCES = "UPDATE_MEDICINCES";
export const LOADING_MEDICINCES = "LOADING_MEDICINCES";
export const ERROR_MEDICINCES = "ERROR_MEDICINCES";

export const GET_PATIENTSDATA = "GET_PATIENTSDATA";
export const LOADING_PATIENTS = "LOADING_PATIENTS";
export const ERROR_PATIENTS = "ERROR_PATIENTS";
export const ADD_PATIENTS = "ADD_PATIENTS";
export const DELETE_PATIENTS = "DELETE_PATIENTS";
export const UPDATE_PATIENTS = "UPDATE_PATIENTS";

export const GET_DOCTORSDATA = "GET_DOCTORSDATA";
export const LOADING_DOCTORSDATA = "LOADING_DOCTORSDATA";
export const ERROR_DOCTORSDATA = "ERROR_DOCTORSDATA";
export const ADD_DOCTORSDATA = "ADD_DOCTORSDATA";
export const DELETE_DOCTORSDATA = "DELETE_DOCTORSDATA";
export const UPDATE_DOCTORSDATA = "UPDATE_DOCTORSDATA";